services:
  - type: web
    name: samcro-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: DASHBOARD_USER
        sync: false
      - key: DASHBOARD_PASS
        sync: false
